version: '3'
services:
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   environment:
  #       - TZ=Asia/Shanghai
  #       - MONGO_INITDB_DATABASE=quantaxis
  #       - MONGO_INITDB_ROOT_USERNAME=admin
  #       - MONGO_INITDB_ROOT_PASSWORD=pass
  #   volumes:
  #     - ./_data_:/data
  #   ports:
  #     - 27017:27017
  # mongo-express:
  #   image: mongo-express
  #   container_name: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
#--
  iqaunt:
    build: .
    image: iqaunt:latest
    container_name: iqaunt
    environment:
        - TZ=Asia/Shanghai
        - MONGODB="admin:pass@mongo"
    volumes:
      - ./_notebooks_:/home
    ports:
      - 8010:8888
      - 8888:8888
    # depends_on:
    #     - mongo
    # links:
    #     - mongo
