version: '3'

services:
  web:
    restart: always
    container_name: py3-web
    image: py3
    build: .
    volumes:
      - ./web:/app
    ports:
      - 8000:8000
    entrypoint:
        - /bin/sh
        - -c
        - |
            pip install -r /app/requirements.txt 
            cd /app && gunicorn -b 0.0.0.0:8000 -w 2 server:app
    
#   redis:
    # image: redis